config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :pages, only: [:index, :show]
  get 'about', to: 'pages#about'
  get 'work', to: 'pages#work'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
	<head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="regular_wrapper_about">
    <nav class="topnav">
      <%= link_to "Home", root_path %>
      <%= link_to "Job history", work_path %>
      <%= link_to "About", about_path %>
      <a href="contact" data-toggle="modal" data-target="#exampleModal">Contact</a>
    </nav>
      <div class="about_content col-6 col-md-4">
        <h1>Thank you so much for taking the time to look at my work. Here is a little info about me.</h1>
        <p>My name is Gabriel Maestas. I'm married to my highschool sweet heart Rubi. We have two beautiful girls Ellie and Emersyn. We love to spend our time outdoors fishing, hiking, or just going to the park. My family is everything to me which is why I chose to become a developer.
        </p>

        <p>In an evolving world where computers are more widely used, following this career path would ensure job security for years to come. Not only is coding a secure job for the future it's something I have been interested in since I was a child. I've always loved to figure out how things work and how to make them run even better. That paired with my love for computers made this choice an easy one.
        </p>

        <p>When i'm not working on my development career or hanging out with my family, you can find me relaxing and enjoying my hobbies. They consist of building and modifying pc's, video games, playing instruments, and sport shooting. I mainly play RPG games on my pc that I built. I also play guitar and piano which my kids love to join in and help me play.
        </p>
      </div>

    <div class="pic col-6 col-md-4"></div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Contact Info</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Phone - (520)820-3023
            <br//>
            E-mail - gabrielmaestas20@gmail.com
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="body_p">
    <nav class="topnav">
      <%= link_to "Home", root_path %>
      <%= link_to "Job history", work_path %>
      <%= link_to "About", about_path %>
      <a href="contact" data-toggle="modal" data-target="#exampleModal">Contact</a>
    </nav>
  	<div class="parallax_wrapper">
      <div class="content">
  			<p>Hi. My name is Gabriel Maestas. I'm an aspiring developer that would be a perfect match for your team.
  			</p>
  			
  			<p>I believe I would be the perfect candidate because I have a strong grasp of html and css. I also have a working knowledge of rails and javascript.
  			</p>

        <p>I am eager and ready to learn whatever programming language I would need to know for the projects that come my way.
        </p> 
  		</div>
  	</div>
  	<div class="regular_wrapper">
  		<div class="content">
  			<p>My dream job has always been developement. From working on company intranets to websites for the mass public to view I've always wanted to put my creative spin on whatever platform I am on.
  			</p>

        <p>I'm also determined to continue working towards creating applications or even being part of a team as big as Microsoft or Google to bring innovative programs to market.
        </p>
  		</div>
  	</div>
  	<div class="parallax_wrapper">
  		<div class="content">
  			<p>A brief history of my work experience has been going from the fast food industry to call centers. I started my journey working the fry station at What-A-Burger. I worked there until I saved enough for a GED test.
  			</p>

        <p>Once I had my GED, I moved up to higher paying call centers. I've worked for Verizon, Dish Network, and Citibank.
        </p> 
  		</div>
  	</div>
  	<div class="regular_wrapper">
  		<div class="content">
  			<p>Here are the links to my git repository and my heroku so that you can see my projects. I hope you enjoy what you see and there will definitely be more to come.
  			</p>

        <p>Feel free to contribute places to the Nomster app or quotes to the Splurty app.
        </p>

  			<p>Here is my yelp clone Nomster<a href="https://github.com/gabrielm20/gabem_nomster"> Github</a> /<a href="https://nomster-gabriel-maestas.herokuapp.com/"> Heroku</a>
  			</p>

        <p>Here is a random quote generator Splurty<a href="https://github.com/gabrielm20/Splurty"> Github</a> / <a href="https://splurty-gabriel-maestas.herokuapp.com/"> Heroku </a>
        </p>

        <p>Here is the git for this app<a href="https://github.com/gabrielm20/resume"> Github</a>
        </p>
  		</div>
  	</div>
    <%= yield %>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Contact Info</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Phone - (520)820-3023
            <br//>
            E-mail - gabrielmaestas20@gmail.com
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </body>
<html>

app/views/pages/work.html.erb
<!DOCTYPE html>
<html>
	<head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<nav class="topnav">
      <%= link_to "Home", root_path %>
      <%= link_to "Job history", work_path %>
      <%= link_to "About", about_path %>
      <a href="contact" data-toggle="modal" data-target="#exampleModal">Contact</a>
    </nav>
    <div class="regular_wrapper_work">    	
    	<div class="work_content col-md">
    		Citibank
    		<p>My most recent job was as a collections specialist for Citibank. I would make outbound calls to people that were behind on their credit card payments and use negotioation tactics to resolve the accounts. In order to succeed we had to hit strict goals. When we fell behind we had a coach there to give us constructive criticism. Working here gave me the ability to focus on whats important and be persistant.
    		</p>
    	</div>
    	<div class="work_content col-md">
    		Dish Network
    		<p>My time at Dish Network started out with me being entry level technical support. I was able to promote twice into the position of broadband specialist. Each department I worked in taught me to think logicaly and give precise directions to customers. Now instead of trying random ways to fix something I take a structured approach for quick and efficient resolutions.
    		</p>
    	</div>
    	<div class="work_content col-md">
    		Afni
    		<p>Afni was my first call center job. At Afni, I worked their Verizon Wireless customer service contract. This is the job that majorly influenced my desicion to become a developer. Hearing customer frusteration with the company website and even my own with the company intranet made me want to be one of the people to make them better.
    		</p>
    	</div>
    	<div class="work_content col-md">
    		What-A-Burger
    		<p>My first real job was What-A-Burger. It was here that I realized education was needed for a better quality of life. Working in the hot kitchen and slipping on the greasy floor only motivated me to get my GED. No matter how bad a day was I learned to push through and always look forward to a better future.
    		</p>
    	</div>    
    </div>
    <%= yield %>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Contact Info</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Phone - (520)820-3023
            <br//>
            E-mail - gabrielmaestas20@gmail.com
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </body>
<html>